#!/bin/zsh

# Ensure zsh is installed

zsh --version >/dev/null 2>&1

if [ $? -ne 0 ]; then
    echo "Zsh is not installed. Please install zsh first."
    exit 1
fi

# Ensure bat is installed

bat --version >/dev/null 2>&1

if [ $? -ne 0 ]; then
    batcat --version >/dev/null 2>&1
fi

if [ $? -ne 0 ]; then
    echo "Bat is not installed. Please install bat first."
    exit 1
fi

mkdir -p ~/.zsh/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git  ~/.zsh/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-completions.git    ~/.zsh/plugins/zsh-completions

# Make ~/.zshrc a symlink to ./.zshrc

ln -sf $(pwd)/.zshrc ~/.zshrc

echo "Zsh plugins installed and .zshrc configured. Please restart your terminal or run 'source ~/.zshrc' to apply changes."

