#!/bin/zsh

mkdir -p ~/.zsh/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git  ~/.zsh/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-completions.git    ~/.zsh/plugins/zsh-completions

# Make ~/.zshrc a symlink to ./.zshrc

ln -sf $(pwd)/.zshrc ~/.zshrc

echo "Zsh plugins installed and .zshrc configured. Please restart your terminal or run 'source ~/.zshrc' to apply changes."

